### ISSUE TITLE
Tweak installation instructions to omit `deno install`

### ISSUE THREAD

**Issue by filmaj** [jhechtf/code-coverage#2]
Thanks for the great project! Love it.

What do you think about removing the instruction to run `deno install` from the README, and instead just invoke the `cli.ts` directly via `deno run` as part of a deno task? This is how I set it up on my project without any additional steps and it works great:

```
cat deno.json
...
  "tasks": {
    "test": "deno fmt --check && deno lint && deno test --allow-read --allow-net src",
    "coverage": "deno test --allow-read --allow-net --coverage=.coverage src && deno coverage --exclude=fixtures --exclude=test --lcov --output=lcov.info .coverage && deno run --allow-read https://deno.land/x/code_coverage@0.2.0/cli.ts"
  }
...
```

I basically added the `--lcov --output=lcov.info` flags to the `deno coverage` invocation and then added the call to `deno run --allow-read https://deno.land/x/code_coverage@0.2.0/cli.ts` at the end.

**Comment by jhechtf** [comment]
Yeah that works for me, especially because in most cases this shouldn't be ran directly, and with a majority of Deno users using a version that has `task` support, makes more sense to note its usage that way.
